# Generated by Django 5.0.6 on 2024-05-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projekat_pretplata_korisnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=40)),
                ('deskripcija', models.TextField(blank=True)),
                ('text', models.TextField(max_length=12000)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='postovi/')),
                ('kreirao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.korisnik')),
            ],
        ),
    ]
