# Generated by Django 5.0.6 on 2024-05-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deskripcija',
        ),
    ]
