# Generated by Django 5.0.6 on 2024-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tehnologija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('slika', models.ImageField(upload_to='tehnologije/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projekat',
            name='pretplata',
        ),
        migrations.RemoveField(
            model_name='projekat',
            name='tehnologije',
        ),
        migrations.AddField(
            model_name='projekat',
            name='tehnologije',
            field=models.ManyToManyField(to='home.tehnologija'),
        ),
    ]
