# Generated by Django 5.0.6 on 2024-05-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projekat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekat',
            name='slug',
        ),
    ]
