# Generated by Django 5.0.6 on 2024-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_projekat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
