# Generated by Django 5.0.6 on 2024-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projekat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekat',
            name='tezina',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
