# Generated by Django 5.0.6 on 2024-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projekat_tezina'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekat',
            name='verzija',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='projekat',
            name='verzija_stage',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('rc', 'Release Candidate (RC)'), ('ga', 'Stable/General Availability (GA)')], default='alpha', max_length=10),
        ),
    ]
