# Generated by Django 5.0.6 on 2024-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_projekat_verzija_projekat_verzija_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekat',
            name='tezina',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='projekat',
            name='verzija_stage',
            field=models.CharField(choices=[('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Release Candidate (RC)', 'Release Candidate (RC)'), ('Stable/General Availability (GA)', 'Stable/General Availability (GA)')], default='Alpha', max_length=32),
        ),
    ]
