# Generated by Django 5.0.6 on 2024-06-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_projekat_tezina_alter_projekat_verzija_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekat',
            name='slika',
        ),
        migrations.CreateModel(
            name='SlikeProjekta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='projekti/slike/')),
                ('projekat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike', to='home.projekat')),
            ],
        ),
    ]
