# Generated by Django 5.0.6 on 2024-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_projekat_slika_slikeprojekta'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='slika',
            field=models.ImageField(blank=True, upload_to='korisnici/slike'),
        ),
    ]
